### Server port ###
server.port=9999
### Springboot application name ###
#spring.application.name=SpringbootH2Database
### Springboot default configuration properties for the h2 database ###
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
### Property to enable the console for the h2 database ###
### Browser url for h2 console - http://localhost:<application_port-no>/h2-console
#spring.h2.console.enabled=true



spring.datasource.url=jdbc:h2:mem:employee-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html